# Generated by Django 3.1.5 on 2021-01-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='avatar',
            field=models.FilePathField(null=True),
        ),
    ]
