# Generated by Django 3.1.5 on 2021-01-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_socialuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='facebook',
            field=models.URLField(null=True),
        ),
    ]
