# Generated by Django 3.1.5 on 2021-01-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_socialuser_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='facebook',
            field=models.URLField(null=True, verbose_name='Facebook Profile'),
        ),
    ]
