# Generated by Django 3.1.5 on 2021-02-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210131_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='socialuser',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='socialuser',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='socialuser',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='socialuser',
            name='site',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='facebook',
            field=models.URLField(null=True),
        ),
    ]
