# Generated by Django 3.1.5 on 2021-02-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210201_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
