# Generated by Django 3.1.5 on 2021-02-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210203_1740'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='socialuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='socialuser',
            name='username',
        ),
    ]
